// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: p2p/proto/tester.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statement string `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *ExecSQLRequest) Reset() {
	*x = ExecSQLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_tester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLRequest) ProtoMessage() {}

func (x *ExecSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_tester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecSQLRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_tester_proto_rawDescGZIP(), []int{0}
}

func (x *ExecSQLRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ExecSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Err    string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ExecSQLResponse) Reset() {
	*x = ExecSQLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_tester_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLResponse) ProtoMessage() {}

func (x *ExecSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_tester_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecSQLResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_tester_proto_rawDescGZIP(), []int{1}
}

func (x *ExecSQLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecSQLResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_p2p_proto_tester_proto protoreflect.FileDescriptor

var file_p2p_proto_tester_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2e, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x3b, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0x43, 0x0a, 0x06,
	0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x53, 0x51, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x78, 0x65, 0x63, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_proto_tester_proto_rawDescOnce sync.Once
	file_p2p_proto_tester_proto_rawDescData = file_p2p_proto_tester_proto_rawDesc
)

func file_p2p_proto_tester_proto_rawDescGZIP() []byte {
	file_p2p_proto_tester_proto_rawDescOnce.Do(func() {
		file_p2p_proto_tester_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_proto_tester_proto_rawDescData)
	})
	return file_p2p_proto_tester_proto_rawDescData
}

var file_p2p_proto_tester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_p2p_proto_tester_proto_goTypes = []interface{}{
	(*ExecSQLRequest)(nil),  // 0: proto.ExecSQLRequest
	(*ExecSQLResponse)(nil), // 1: proto.ExecSQLResponse
}
var file_p2p_proto_tester_proto_depIdxs = []int32{
	0, // 0: proto.Tester.Insert:input_type -> proto.ExecSQLRequest
	1, // 1: proto.Tester.Insert:output_type -> proto.ExecSQLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p2p_proto_tester_proto_init() }
func file_p2p_proto_tester_proto_init() {
	if File_p2p_proto_tester_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p2p_proto_tester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecSQLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_tester_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecSQLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_proto_tester_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p2p_proto_tester_proto_goTypes,
		DependencyIndexes: file_p2p_proto_tester_proto_depIdxs,
		MessageInfos:      file_p2p_proto_tester_proto_msgTypes,
	}.Build()
	File_p2p_proto_tester_proto = out.File
	file_p2p_proto_tester_proto_rawDesc = nil
	file_p2p_proto_tester_proto_goTypes = nil
	file_p2p_proto_tester_proto_depIdxs = nil
}
